### ISSUE TITLE
Could not run example ImageFiltering and ImageFilteringWithBLob examples in Processing 3

### ISSUE THREAD

**Issue by OneTimeUser** [jorditost/ImageFiltering#1]
Not sure if you are keeping these updated.  Haven't come across any documentation of others having issues but these are not running with Processing 3.   The console error output is as follows:

`java.lang.RuntimeException: Waited 5000ms for: <5c2d4feb, 52eaaa1e>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1>
    at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:449)
    at java.lang.Thread.run(Thread.java:745)
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.
`

Just wanted to let you know.

**Comment by jorditost** [comment]
Thanks for your feedback. I didn't tested it with Processing 3, but I will take a look. 

If you found already a solution, feel free to fork the repo and do a push request.

**Comment by OneTimeUser** [comment]
Haven't yet. Was just poking around but I'll see if I can get to it at some
point. Thanks
